package protocols;

import asn1.com.ASN1Definitions;

public interface Tags extends ASN1Definitions {

	/********************************************    T A G S    ********************************************/
	final static short ASN1_T_NFE 							= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_10;
	final static short ASN1_T_NFE_SOURCE_ENTITY 			= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_NFE_SOURCE_ENTITY_ADDRESS 	= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_NFE_DEST_ENTITY 				= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_NFE_DEST_ENTITY_ADDRESS 		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_NFE_ENTITY_TYPE 				= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	
	final static short ASN1_T_INTERPRETATION_APDU 			= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_11;
	
	final static short ASN1_T_INVOKE_PDU					= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_RETURN_RESULT_PDU				= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_RETURN_ERROR_PDU				= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_REJECT_PDU					= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_4;
	
	final static short ASN1_T_INVOKE_ID						= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_INT;
	final static short ASN1_T_LINKED_ID						= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_RETURN_RESULT_OPERATION 		= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_REJ_GENERAL					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_REJ_INVOKE					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_REJ_RETURN_RESULT				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_REJ_RETURN_ERROR				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	
	final static short ASN1_T_OPERATION_LOCAL_VALUE			= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_INT;
	final static short ASN1_T_OPERATION_GLOBAL_VALUE		= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_OBJ_ID;
	
	final static short ASN1_T_ERROR_LOCAL_VALUE				= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_INT;
	final static short ASN1_T_ERROR_GLOBAL_VALUE			= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_OBJ_ID;
	final static short ASN1_T_ERROR_UNSPECIFIED				= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_NUM_PARTY_NUM_UNKNOWN 		= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_NUM_PARTY_NUM_PUBLIC 			= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_NUM_PARTY_NUM_DATA 			= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_3;
	final static short ASN1_T_NUM_PARTY_NUM_TELEX 			= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_4;
	final static short ASN1_T_NUM_PARTY_NUM_PRIVATE 		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_NUM_PARTY_NUM_NATIONAL		= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_8;

	final static short ASN1_T_NUM_PUBLIC_TON 				= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_NUM_PRIVATE_TON 				= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_NUM_NUMBER_DIGITS				= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_NUM_STR;
	final static short ASN1_T_NUM_SCREENING_IND				= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_NUM_USER_SUBADDRESS			= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_NUM_SUBADDRESS_INFO			= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_OCTET_STR;
	final static short ASN1_T_NUM_ODD_COUNT_IND				= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_BOOLEAN;
	final static short ASN1_T_NUM_NSAP_SUBADDRESS			= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_OCTET_STR;
	final static short ASN1_T_NUM_PRES_ALLOWED_IND			= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_BOOLEAN;
	
	final static short ASN1_T_EXTENSION						= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_EXTENSION_VALUE				= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_OBJ_ID;

	final static short ASN1_T_CO_EXT_NONE	 				= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_NULL;
	final static short ASN1_T_CO_EXTENSION_TAG_1 			= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_CO_EXTENSION_TAG_2 			= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_2;
	
	final static short ASN1_T_PR_EXTENSION	 				= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_NULL;
	final static short ASN1_T_PR_SERVICE_LIST	 			= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_BIT_STR;
	final static short ASN1_T_PR_EXT_SERVICE_LIST	 		= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_SUBADDR_TRANS_ARG	 			= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_SUBADDR_ARG_EXT	 			= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_SUBADDR_ARG_SEQ_OF_EXT		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_1;

	final static short ASN1_T_CT_UPDATE_ARG	 				= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CT_UPDATE_ARG_EXT	 			= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_9;
	final static short ASN1_T_CT_UPDATE_ARG_SEQ_OF_EXT		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_10;

	final static short ASN1_T_QSIG_IE	 					= APPLICATION 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_BASIC_SERVICE	 				= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_ENUM;

	final static short ASN1_T_CT_ACTIVE_ARG	 				= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CT_ACTIVE_ARG_EXT	 			= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_9;
	final static short ASN1_T_CT_ACTIVE_ARG_SEQ_OF_EXT		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_10;
	
	final static short ASN1_T_CT_COMPLETE_ARG	 			= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CT_ARGUMENT_EXT	 			= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_9;
	final static short ASN1_T_CT_ARGUMENT_SEQ_OF_EXT		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_10;
	
	final static short ASN1_T_CT_END_DESIGNATION	 		= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_CT_CALL_STATUS	 			= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_ENUM;

	final static short ASN1_T_EXT_ARG_SEQ	 				= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CORNET_IE	 					= APPLICATION 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AREA_ID						= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_NAME_ARG_CHOICE_SEQ	 		= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_NAME_EXTENSION	 			= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_NAME_SEQ_OF_EXTENSION			= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_6;
	
	final static short ASN1_T_NAME_NOT_AVAILABLE	 		= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_4;
	final static short ASN1_T_NAME_NOT_AVAILABLE_REST	 	= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_7;
	final static short ASN1_T_NAME_DATA	 					= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_OCTET_STR;
	final static short ASN1_T_NAME_SET	 					= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_NAME_CHARACTER_SET	 		= UNIVERSAL 	| PRIMITIVE 	| ASN1_TAG_INT;
	
	final static short ASN1_T_NAME_PRES_ALLOWED_SIMPLE	 	= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_NAME_PRES_ALLOWED_EXT	 		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_NAME_PRES_RESTR_SIMPLE	 	= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_NAME_PRES_RESTR_EXT	 		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_NAME_PRES_RESTR_NULL	 		= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_7;
	
	final static short ASN1_T_NUM_PRES_ALLOWED	 			= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_NUM_PRES_RESTR	 			= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_NUM_NA_INTERW	 				= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_NUM_PRES_RESTR_ADR	 		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_3;
	
	final static short ASN1_T_NQ_DIVERSION_REASON_HISTORY	= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CF_NQ_REROUTING_ARG	 		= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CLASSMARKS_AP1				= APPLICATION 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_CALLED_AREA_ID				= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_LAST_REROUTING_AREA_ID		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_CALLING_AREA_ID				= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_ORIGINAL_CALLED_AREA_ID4		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_CF_NQ_ADDITIONAL_INFO_5		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_DIV_LEG_1_EXTENSION			= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DIV_LEG_2_EXTENSION			= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DIV_LEG_3_EXTENSION			= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_DIVERTING_AREA_ID				= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_ORIGINAL_CALLED_AREA_ID3		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_CF_NQ_ADDITIONAL_INFO_4		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_4;
	
	final static short ASN1_T_CD_REDIRECTING_NAME			= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_NOMINATED_AREA_ID				= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_1;
	
	final static short ASN1_T_CD_CHECK_RESTRICTION_EXT		= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CD_CLASSMARKS_CP0				= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_SERVED_USER_NR_AREA_ID		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_DIVERTED_TO_NR_AREA_ID		= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_2;
	
	final static short ASN1_T_CD_INTERROGATE_EXT			= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CD_CLASSMARKS_CP1				= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_CD_P_IN						= CONTEXT 		| PRIMITIVE 	| ASN1_TAG_2;
	
	final static short ASN1_T_CD_DEACTIVATE_EXT				= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_CD_ACTIVATE_EXT				= UNIVERSAL 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DIVERTED_TO_AREA_ID			= CONTEXT 		| CONSTRUCTED 	| ASN1_TAG_0;
	
	final static short ASN1_T_CF_EXTENSION_TAG_1			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_CF_EXTENSION_TAG_2			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_CF_EXTENSION_TAG_3			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_CF_EXTENSION_TAG_4			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_CF_EXTENSION_TAG_5			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_CF_EXTENSION_TAG_6			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_6;
	final static short ASN1_T_CF_EXTENSION_TAG_9			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_9;
	final static short ASN1_T_CF_EXTENSION_TAG_10			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_10;
	
	final static short ASN1_T_CF_EXT_NONE					= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_NULL;
	final static short ASN1_T_CF_EXT_SINGLE					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CF_EXT_MULTIPLE				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ_OF;
	
	final static short ASN1_T_CF_EXTENSION_SEQ				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_REDIR_NAME_DIV_LEG_INFO3		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_CF_DIV_LEG_INFO3_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_CF_DIV_LEG_INFO2_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_CF_SUBSCRIPTION_OPTION		= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_CF_DIVERSION_REASON			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_CF_ORIGINAL_DIVERSION_REASON	= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_CF_DIVERSION_COUNTER			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;
	
	final static short ASN1_T_DIV_NR_DIV_LEG_INFO2			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_OR_CALLED_NR_DIV_LEG_INFO2	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_RED_NAME_DIV_LEG_INFO2		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_OR_CALLED_NAME_DIV_LEG_INFO2	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;

	final static short ASN1_T_CF_DIV_LEG_INFO1_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CF_DIV_LEG_INFO1_ARG_EXT		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_CF_DIV_LEG_INFO1_EXT_NNA		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_4;
	
	final static short ASN1_T_CF_DIVERTION_INFORMATION		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CF_DIV_INF_CALLED_ADDRESS		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_CF_DIV_INF_OR_CALLED_ADDRESS	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_CF_DIV_INF_LAST_DIV_NUM		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_CF_DIV_INF_LAST_DIV_RER_AD	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_CF_DIV_INF_USER_INFORMATION	= APPLICATION	| PRIMITIVE 	| ASN1_TAG_0;
	
	final static short ASN1_T_CF_CALL_REROUTEING			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CF_REROUTEING_COUNTER			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;
	final static short ASN1_T_CF_LAST_REROUTEING_NR			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_CF_REROUTEING_SUBSCR_OPTION	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_CF_REROUTEING_CALLING_SUBADD	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	
	final static short ASN1_T_CF_ACT_DIV_ARG				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CF_ACT_STATUS_NOTI_DIV_ARG	= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CF_DEACT_DIV_ARG				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CF_DEACT_STATUS_NOTI_DIV_ARG	= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CF_INTERROGATION_DIV_ARG		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_CF_ALL_NUMBERS				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_NULL;
	final static short ASN1_T_CF_ALL_SERVICES				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_NULL;
	final static short ASN1_T_CF_PROCEDURE					= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_CF_BASIC_SERVICE				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_CF_FORW_TO_ADDRESS			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CF_SERVED_USER_NR_LIST		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SET_OF;
	final static short ASN1_T_CF_INT_RESULT_LIST			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SET_OF;
	final static short ASN1_T_CF_INT_RESULT					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_SUBSCRIPTION_OPTION_CR_S0		= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_SUBSCRIPTION_OPTION_TAG_2		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	
	final static short ASN1_T_NUM_ADDRESS					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_LAST_REROUTING_NR_CR			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_SUBSCRIPTION_OPTION_CR		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_CALLING_PARTY_SUBADRESS_CR	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_CALLING_NUMBER_CR				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_CALLING_NAME_CR				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_ORIGINAL_CALLED_NR_CR			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_6;
	final static short ASN1_T_REDIRECTING_NAME_CR			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_7;
	final static short ASN1_T_ORIGINAL_CALLED_NAME_CR		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_8;
	final static short ASN1_T_CF_CALL_REROUTING_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CF_CALL_REROUTING_RES_NULL	= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_NULL;
	
	final static short ASN1_T_CF_CHECK_RESTRICTION_ARG		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_RI_CALLING_ROUTING_INFO		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_RI_CALLED_ROUTING_INFO		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_RI_CONNECT_ROUTING_INFO		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_RI_AREA_ID_ZERO				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_RI_AREA_ID_ONE				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_RI_AREA_ID_TWO				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_RI_AREA_ID_VALUE				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;
	
	final static short ASN1_T_CI_COMPLETED_INV_NULL			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_NULL;

	final static short ASN1_T_CI_EXTENSION_TAG_1			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_CI_EXTENSION_TAG_2			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	
	final static short ASN1_T_CI_GET_CIPL_INV_NULL			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_NULL;
	final static short ASN1_T_CI_GET_CIPL_RES				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CI_PROTECTION_LEVEL			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;

	final static short ASN1_T_CI_REQUEST_RES				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CI_UNWANTED_USER_STATUS		= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_CI_REQUEST_ARG				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CI_CAPABILITY_LEVEL			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	
	final static short ASN1_T_NQ_CORNET_N_SEQ				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_NQ_CORNET_N_MSG_TYPE			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_NQ_CORNET_N_CS0_DATA			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_NQ_CORNET_N_CS7_DATA			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	
	final static short ASN1_T_CSTA_ORIG_WANTED				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;
	final static short ASN1_T_CSTA_ACD_GROUP				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;
	final static short ASN1_T_CSTA_VIRT_ACD_GROUP_SEQ		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CSTA_DAD_DUWA_5				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_CSTA_DAD_4					= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_CSTA_OAD_3					= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_CSTA_CAD_2					= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_CSTA_RNAD_1					= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_CSTA_RGAD_0					= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_CSTA_SERVICE					= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;
	final static short ASN1_T_CSTA_SERVICE_ARG				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_MEDIA_CALL_CHAR				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DEVID_DIALING_NUM				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_DEVID_DEVICE_NUM				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_DEVID_IMPL_PUBLIC				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_DEVID_EXPL_PUBLIC				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_DEVID_IMPL_PRIVATE			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_4;
	final static short ASN1_T_DEVID_EXPL_PRIVATE			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_DEVID_OTHER					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_6;
	final static short ASN1_T_DEVID_PRIV_TON_UNKNOWN		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_DEVID_PRIV_TON_L3_REG_NUM		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_DEVID_PRIV_TON_L2_REG_NUM		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_DEVID_PRIV_TON_L1_REG_NUM		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	final static short ASN1_T_DEVID_PRIV_TON_SPEC_NUM		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_4;
	final static short ASN1_T_DEVID_PRIV_TON_LOCAL_NUM		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_5;
	final static short ASN1_T_DEVID_PRIV_TON_ABBREV			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_6;
	final static short ASN1_T_DEVID_PUBL_TON_UNKNOWN		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_DEVID_PUBL_TON_INTERNAT		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_DEVID_PUBL_TON_NATIONAL		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_DEVID_PUBL_TON_NW_SPEC		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	final static short ASN1_T_DEVID_PUBL_TON_SUBSCR			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_4;
	final static short ASN1_T_DEVID_PUBL_TON_ABBREV			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_5;
	
	final static short ASN1_T_MCC_MEDIA_CLASS				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_BIT_STR;
	final static short ASN1_T_MCC_CONNECTION_RATE			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_MCC_BIT_RATE					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_MCC_DELAY_TOLERENCE			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_MCC_SW_SUBDOMAIN_CCIE_TYPE	= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	final static short ASN1_T_MCC_SW_SUBDOMAIN_CCIE			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_OCTET_STR;
	
	final static short ASN1_T_CCBS_REQUEST_RESULT			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CCBS_RECALL_MODE				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_CCBS_REFERENCE				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;
	
	final static short ASN1_T_CCBS_INTERROGATE_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CCBS_INTERROGATE_RES			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CCBS_CALL_DETAILS				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CCBS_CALL_INFORMATION			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_CCBS_ERASE_ARG				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CCBS_ERASE_REASON				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	
	final static short ASN1_T_CCBS_REMOTE_USER_FREE_ARG		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CCBS_B_FREE_ARG				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CCBS_CALL_ARG					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CCBS_STATUS_REQUEST_ARG		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CCBS_STATUS_REQUEST_RES		= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_BOOLEAN;
	
	final static short ASN1_T_STATUS_REQUEST_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_STATUS_RESULT					= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_STAT_REQ_COMP_MODE			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;

	final static short ASN1_T_CCBS_Q931_INFO_ELE			= APPLICATION	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_CCBS_CALL_LINKAGE_ID			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;

	final static short ASN1_T_CCBS_T_REQUEST_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CCBS_T_DEST_ADDRESS			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CCBS_T_RETENTION_SUPP_ARG		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_CCBS_T_PRES_ALLOWED_IND		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_CCBS_T_ORIGINATING_ADDR		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CCBS_T_RETENTION_SUPP_RES		= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_BOOLEAN;

	final static short ASN1_T_NQCC_GATEWAY_INFO_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_NQCC_GATEWAY_AREA_ID			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_NQCC_BASIC_CALL_ID			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;

	final static short ASN1_T_CC_EXT_NONE					= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_NULL;
	final static short ASN1_T_CC_EXT_MULTIPLE				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ_OF;
	
	final static short ASN1_T_CC_SUBADDR_A					= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_10;
	final static short ASN1_T_CC_SUBADDR_B					= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_11;
	final static short ASN1_T_CC_REQUEST_RES				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CC_NO_PATH_RES				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_CC_RETAIN_SER					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_CC_REQUEST_ARG				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CC_CAN_RETAIN_SERVICE			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_12;
	final static short ASN1_T_CC_RETAIN_SIG_CONN			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_13;
	final static short ASN1_T_CC_OPT_ARG_FULL_ARG			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_0;
	
	final static short ASN1_T_APN_ARG						= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_APN_NUMBER_CATEGORY			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_BIT_STR;
	
	final static short ASN1_T_PSS_DMC						= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_PSS_TGK						= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	
	final static short ASN1_T_SPE_SECURITY_PARAMETER_RES	= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_SPE_SECURITY_PARAMETER_ARG	= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_SPE_INC_TRUNK_SEC_PARAMETER	= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_SPE_DMC_KEY_MATERIAL			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_SPE_PAYLOAD_ENC_PARAM_RET		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_SPE_PAYLOAD_ENC_PARAM_ARG		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_SPE_DMC_SECURITY_PARAM		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_DMC_DATA_EXC_ARG				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DMC_DATA_EXC_RES				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DMC_DATA_UPDATE				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DMC_DATA_EXC_INVITE			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DMC_CURRENT_DMC_DATA			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DMC_CORR_ID_STRUCTURED		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DMC_THREAD_ID					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DMC_GLOBAL_ID					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DMC_AREA_ID					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_DMC_IP_4_ADDRESS				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_DMC_IP_6_ADDRESS				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_DMC_FAX_CAPABILITY			= CONTEXT		| PRIMITIVE		| ASN1_TAG_1;
	
	final static short ASN1_T_MWI_ACTIVATE_ARG				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_MWI_DEACTIVATE_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_MWI_INDICATE_ARG				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_MWI_ACT_EXTENSION_TAG_6		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_6;
	final static short ASN1_T_MWI_ACT_EXTENSION_TAG_7		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_7;
	final static short ASN1_T_MWI_DEACT_EXTENSION_TAG_3		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_MWI_DEACT_EXTENSION_TAG_4		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_MWI_MSG_CENTREID_INTEGER		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_MWI_MSG_CENTREID_PTYNUM		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_MWI_MSG_CENTREID_NUM_STR		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_MWI_NB_OF_MESSAGES			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	final static short ASN1_T_MWI_ORIGINATING_NR			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_MWI_TIME_STAMP				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_GEN_TIME;
	final static short ASN1_T_MWI_PRIORITY					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_5;
	final static short ASN1_T_MWI_DUM_RES_NULL				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_NULL;
	final static short ASN1_T_MWI_DUM_RES_EXTENSION			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_MWI_DUM_RES_EXT_MULTI			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_MWI_ACT_T_CONTR_USER_NR		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_MWI_ACT_T_NB_OF_MESSAGES		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_MWI_ACT_T_ORIG_PROV_NR		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_MWI_ACT_T_TIME_STAMP			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_MWI_ACT_T_MESSAGE_ID			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_MWI_IND_T_CONTR_USER_NR		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_MWI_IND_T_BASIC_SERVICE		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_MWI_IND_T_NB_OF_MESSAGES		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_MWI_IND_T_ORIG_PROV_NR		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_MWI_IND_T_TIME_STAMP			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_MWI_IND_T_MESSAGE_ID			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_6;
	final static short ASN1_T_MWI_MODE_TAG					= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_6;
	final static short ASN1_T_MWI_INVOCATION_MODE_TAG		= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_ENUM;
	final static short ASN1_T_MWI_MSG_ID					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_NQ_CONF_MEMBER_ELEMENT		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_NQ_CONF_MEMBER_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_NQ_CONF_MEMBER_NAME			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_NQ_CONF_MEMBER_AREA_ID		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	
	final static short ASN1_T_NQ_PREP_EXT					= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_NQ_PREP_SEQ_OF_EXT			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_NQ_PR_SETUP					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_NQ_PR_PROPOSE					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_CINT_EXT_NONE					= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_NULL;
	final static short ASN1_T_CINT_EXTENSION_TAG_5			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_CINT_EXTENSION_TAG_6			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_6;
	final static short ASN1_T_CINT_INTERCEPTION_CAUSE		= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;
	final static short ASN1_T_CINT_LEG_INFORMATION_1_ARG	= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;	
	final static short ASN1_T_CINT_CALLED_NUMBER_TAG1		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_CINT_OR_CALLED_NUMBER_TAG2	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_CINT_CALLED_NAME_TAG3			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_CINT_OR_CALLED_NAME_TAG4		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_CINT_LEG_INFORMATION_2_ARG	= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CINT_OR_CALLED_NUMBER_TAG1	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_CINT_CALLED_NAME_TAG2			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_CINT_OR_CALLED_NAME_TAG3		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_CINT_CONDITION_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_RECALL_EXTENSION_TAG_6		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_6;
	final static short ASN1_T_RECALL_EXTENSION_TAG_7		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_7;
	final static short ASN1_T_RECALL_ALERTING_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_RECALL_ANSWERED_ARG			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_RECALL_CONNECTED_NUMBER		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_RECALL_ALERTED_NUMBER			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_RECALL_CONNECTED_SUBADDRESS	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_RECALL_CONNECTED_NAME			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_RECALL_ALERTED_NAME			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	
	final static short ASN1_T_CICL_ASSIGN					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CICL_UPDATE					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CICL_CALL_ID_DATA				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CICL_GLOBAL_CALL_ID			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_CICL_THREAD_ID				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_CICL_LEG_ID					= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_CICL_SW_SUB_DOMAIN_NAME		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_CICL_TIME_STAMP				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	final static short ASN1_T_CICL_SUB_DOMAIN_ID			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_CICL_GLOBALLY_UNIQUE_ID		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_CICL_EXTENSION				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_CICL_SEQ_OF_EXTENSION			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_CICL_EXTENSION_SEQ			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CICL_CALLING_ID				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_CICL_IN_OUT_NW_TRUNK_ID		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_CICL_PUBLIC_TRUNK_ID			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_CICL_CALLED_ID				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_CICL_DEVICE_ID				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CICL_CALL_ID					= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;
	
	final static short ASN1_T_ID_OF_CALL					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_ID_CALL_THREAD_CRE_AREA_ID	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_ID_CALL_GLOBAL_CRE_AREA_ID	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	
	final static short ASN1_T_CMN_ARGUMENT					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CMN_INFORMATION				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_CMN_FEATURE_ID				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_CMN_SSDND_OPER_LEVEL			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	final static short ASN1_T_CMN_SSCI_PROTECTION_LEVEL		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_4;
	final static short ASN1_T_CMN_EQUIPMENT_ID				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_CMN_PARTY_CATEGORY			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_6;
	final static short ASN1_T_CMN_NODE_ID					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_CMN_GROUP_ID					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_CMN_UNIT_ID					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	final static short ASN1_T_CMN_EXT_SINGLE_TAG_1			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_CMN_EXT_MULTIPLE_TAG_2		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_CMN_EXT_SINGLE_TAG_7			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_7;
	final static short ASN1_T_CMN_EXT_MULTIPLE_TAG_8		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_8;
	
	final static short ASN1_T_EMERGENCY_CALL_NUMBER			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	
	final static short ASN1_T_SSCT_SETUP					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_SSCT_INITIATE					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_SSCT_PRES_ADDRESS_SCREENED	= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_SSCT_NAME						= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_SSCT_SIMPLE_EXTENSION			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_SSCT_MULTIPLE_EXTENSION		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_SSCT_TRANSFERRED_NAME			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_SSCT_TRANSFERRING_ADDRESS		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_SSCT_TRANSFERRING_NAME		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_SSCT_SIMPLE_EXTENSION_3		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_SSCT_MULTIPLE_EXTENSION_4		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_SSCT_SIMPLE_EXTENSION_4		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_SSCT_MULTIPLE_EXTENSION_5		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_SSCT_SETUP_EXTENSION			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_SSCT_TRANSFERRING_AREA_ID		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_SSCT_INITIATE_EXTENSION		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_SSCT_INIT_EXT_CLASSMARKS		= APPLICATION	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_SSCT_INIT_EXT_RR_AREA_ID		= CONTEXT		| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_SSCT_INIT_EXT_TRING_AREA_ID	= CONTEXT		| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_SSCT_INIT_EXT_TRED_AREA_ID	= CONTEXT		| CONSTRUCTED 	| ASN1_TAG_2;
	
	
	final static short ASN1_T_NQ_RPC_SEQ					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_NQ_RPC_RES_LOCK_ON			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_BOOLEAN;

	final static short ASN1_T_AOC_CHAR_ASS_NUMBER			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_0;
	final static short ASN1_T_AOC_CHAR_ASS_ID				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;
	final static short ASN1_T_AOC_NOT_AVAILABLE				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_NULL;
	final static short ASN1_T_AOC_NUMBER_OF_UNITS			= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;
	final static short ASN1_T_AOC_TYPE_OF_UNIT				= UNIVERSAL	 	| PRIMITIVE 	| ASN1_TAG_INT;
	final static short ASN1_T_AOC_AMOUNT_CURR_AMOUNT		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOC_AMOUNT_MULTIPLIER			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_AOC_REC_CURR_RCURR			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOC_REC_CURR_RAMOUNT			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_AOC_REC_UNITS_LIST			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOC_LENGTH_OF_TIME_UNIT		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOC_SCALE						= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;

	final static short ASN1_T_AOCD_SPEC_CURR_REC_CURR		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_AOCD_SPEC_CURR_TYPE			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_AOCD_SPEC_CURR_BILL_ID		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	final static short ASN1_T_AOCD_CURR_INFO_SPEC_CURR		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCD_CURR_INFO_FREE			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOCD_C_U_I_REC_UNIT_LIST		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_AOCD_C_U_I_TYPE_OF_CHAR		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_AOCD_C_U_I_BILLING_ID			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	final static short ASN1_T_AOCD_CHAR_UNIT_INFO_SPEC		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCD_CHAR_UNIT_INFO_FREE		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOCD_C_I_BILLING_ID			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	
	final static short ASN1_T_AOCE_C_I_REC_CURR				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_AOCE_C_I_SPEC_CURR			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCE_C_I_FREE					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOCE_CURR_INFO				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCE_C_U_I_REC_UNIT_LIST		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_AOCE_C_U_I_BILLING_ID			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_AOCE_C_U_I_SPEC_CURR			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCE_C_U_I_FREE				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOCE_CHARGING_UNIT			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	
	final static short ASN1_T_AOCS_CURR_INFO_LIST			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCS_CURR_INFO				= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCS_FREE_OF_CHARGE			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_4;
	final static short ASN1_T_AOCS_CURR_INFO_NOT_AVAIL		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_5;
	final static short ASN1_T_AOCS_DURATION_CURR			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_AOCS_FLAT_RATE_CURR			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_AOCS_VOLUME_RATE_CURR			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_3;
	final static short ASN1_T_AOCS_D_CURR					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOCS_D_AMOUNT					= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_AOCS_D_CHARGING_TYPE			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	final static short ASN1_T_AOCS_D_TIME					= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_4;
	final static short ASN1_T_AOCS_D_GRANULARITY			= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_5;
	final static short ASN1_T_AOCS_FR_CURR					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOCS_FR_AMOUNT				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_AOCS_VR_CURR					= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOCS_VR_AMOUNT				= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
	final static short ASN1_T_AOCS_VR_VOLUME_UNIT			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_3;
	
	final static short ASN1_T_AOCNQ_INTERIM					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCNQ_FINAL					= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCNQ_CHARGE_REQUEST			= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCNQ_INT_CHARGE_NOT_AVAIL	= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_AOCNQ_INT_FREE_OF_CHARGE		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOCNQ_INT_SPECIFIC_CURR		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCNQ_INT_RECORDED_CURR		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_AOCNQ_INT_BILLING_ID			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_AOCNQ_FIN_CHARGE_NOT_AVAIL	= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_0;
	final static short ASN1_T_AOCNQ_FIN_FREE_OF_CHARGE		= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOCNQ_FIN_SPECIFIC_CURR		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCNQ_FIN_RECORDED_CURR		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_1;
	final static short ASN1_T_AOCNQ_FIN_BILLING_ID			= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_2;
	final static short ASN1_T_AOCNQ_ADVICE_MODE_COMB		= UNIVERSAL	 	| CONSTRUCTED 	| ASN1_TAG_SEQ;
	final static short ASN1_T_AOCNQ_EXTENSION				= CONTEXT	 	| PRIMITIVE 	| ASN1_TAG_1;
	final static short ASN1_T_AOCNQ_MULTIPLE_EXTENSION		= CONTEXT	 	| CONSTRUCTED 	| ASN1_TAG_2;
}
